import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Supabase environment variables are missing. Please check NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database types
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          password: string;
          name: string;
          username: string | null;
          role: 'admin' | 'user' | null;
          company_name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          password: string;
          name: string;
          username?: string | null;
          role?: 'admin' | 'user' | null;
          company_name: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          password?: string;
          name?: string;
          username?: string | null;
          role?: 'admin' | 'user' | null;
          company_name?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      currencies: {
        Row: {
          id: string;
          code: string;
          name: string;
          symbol: string;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          symbol: string;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          symbol?: string;
          is_active?: boolean;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          type: 'income' | 'expense';
          color: string;
          is_default: boolean;
          user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: 'income' | 'expense';
          color: string;
          is_default?: boolean;
          user_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'income' | 'expense';
          color?: string;
          is_default?: boolean;
          user_id?: string;
          created_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          name: string;
          email: string | null;
          phone: string | null;
          address: string | null;
          tax_number: string | null;
          contact_person: string | null;
          contract_start_date: string | null;
          contract_end_date: string | null;
          currency_id: string;
          balance: number;
          is_active: boolean;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          tax_number?: string | null;
          contact_person?: string | null;
          contract_start_date?: string | null;
          contract_end_date?: string | null;
          currency_id: string;
          balance?: number;
          is_active?: boolean;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          tax_number?: string | null;
          contact_person?: string | null;
          contract_start_date?: string | null;
          contract_end_date?: string | null;
          currency_id?: string;
          balance?: number;
          is_active?: boolean;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      employees: {
        Row: {
          id: string;
          name: string;
          position: string;
          net_salary: number;
          currency_id: string;
          payroll_period: 'monthly' | 'weekly' | 'biweekly';
          payment_day: number;
          is_active: boolean;
          user_id: string;
          email: string | null;
          phone: string | null;
          address: string | null;
          emergency_contact: string | null;
          contract_start_date: string | null;
          contract_end_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          position: string;
          net_salary: number;
          currency_id: string;
          payroll_period: 'monthly' | 'weekly' | 'biweekly';
          payment_day: number;
          is_active?: boolean;
          user_id: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          emergency_contact?: string | null;
          contract_start_date?: string | null;
          contract_end_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          position?: string;
          net_salary?: number;
          currency_id?: string;
          payroll_period?: 'monthly' | 'weekly' | 'biweekly';
          payment_day?: number;
          is_active?: boolean;
          user_id?: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          emergency_contact?: string | null;
          contract_start_date?: string | null;
          contract_end_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      transactions: {
        Row: {
          id: string;
          type: 'income' | 'expense';
          amount: number;
          currency_id: string;
          category_id: string;
          client_id: string | null;
          employee_id: string | null;
          cash_account_id: string | null;
          description: string;
          notes: string | null;
          transaction_date: string;
          is_vat_included: boolean;
          vat_rate: number;
          is_recurring: boolean;
          recurring_period: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly' | null;
          next_recurring_date: string | null;
          parent_transaction_id: string | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type: 'income' | 'expense';
          amount: number;
          currency_id: string;
          category_id: string;
          client_id?: string | null;
          employee_id?: string | null;
          cash_account_id?: string | null;
          description: string;
          notes?: string | null;
          transaction_date: string;
          is_vat_included?: boolean;
          vat_rate?: number;
          is_recurring?: boolean;
          recurring_period?: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly' | null;
          next_recurring_date?: string | null;
          parent_transaction_id?: string | null;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: 'income' | 'expense';
          amount?: number;
          currency_id?: string;
          category_id?: string;
          client_id?: string | null;
          employee_id?: string | null;
          cash_account_id?: string | null;
          description?: string;
          notes?: string | null;
          transaction_date?: string;
          is_vat_included?: boolean;
          vat_rate?: number;
          is_recurring?: boolean;
          recurring_period?: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly' | null;
          next_recurring_date?: string | null;
          parent_transaction_id?: string | null;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      quotes: {
        Row: {
          id: string;
          quote_number: string;
          client_id: string;
          currency_id: string;
          total_amount: number;
          vat_rate: number;
          vat_amount: number;
          total_with_vat: number;
          status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired';
          valid_until: string;
          notes: string | null;
          terms_conditions: string | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          quote_number: string;
          client_id: string;
          currency_id: string;
          total_amount: number;
          vat_rate?: number;
          vat_amount?: number;
          total_with_vat?: number;
          status?: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired';
          valid_until: string;
          notes?: string | null;
          terms_conditions?: string | null;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          quote_number?: string;
          client_id?: string;
          currency_id?: string;
          total_amount?: number;
          vat_rate?: number;
          vat_amount?: number;
          total_with_vat?: number;
          status?: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired';
          valid_until?: string;
          notes?: string | null;
          terms_conditions?: string | null;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      debts: {
        Row: {
          id: string;
          client_id: string;
          currency_id: string;
          amount: number;
          due_date: string;
          description: string;
          status: 'pending' | 'paid' | 'overdue' | 'cancelled';
          payment_date: string | null;
          notes: string | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          currency_id: string;
          amount: number;
          due_date: string;
          description: string;
          status?: 'pending' | 'paid' | 'overdue' | 'cancelled';
          payment_date?: string | null;
          notes?: string | null;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          currency_id?: string;
          amount?: number;
          due_date?: string;
          description?: string;
          status?: 'pending' | 'paid' | 'overdue' | 'cancelled';
          payment_date?: string | null;
          notes?: string | null;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      cash_accounts: {
        Row: {
          id: string;
          name: string;
          currency_id: string;
          initial_balance: number;
          current_balance: number;
          is_active: boolean;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          currency_id: string;
          initial_balance?: number;
          current_balance?: number;
          is_active?: boolean;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          currency_id?: string;
          initial_balance?: number;
          current_balance?: number;
          is_active?: boolean;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          invoice_number: string;
          client_id: string;
          currency_id: string;
          total_amount: number;
          vat_rate: number;
          vat_amount: number;
          total_with_vat: number;
          status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
          issue_date: string;
          due_date: string;
          payment_date: string | null;
          notes: string | null;
          terms_conditions: string | null;
          is_recurring: boolean;
          recurring_period: 'monthly' | 'quarterly' | 'yearly' | null;
          next_invoice_date: string | null;
          parent_invoice_id: string | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          invoice_number: string;
          client_id: string;
          currency_id: string;
          total_amount: number;
          vat_rate?: number;
          vat_amount?: number;
          total_with_vat?: number;
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
          issue_date: string;
          due_date: string;
          payment_date?: string | null;
          notes?: string | null;
          terms_conditions?: string | null;
          is_recurring?: boolean;
          recurring_period?: 'monthly' | 'quarterly' | 'yearly' | null;
          next_invoice_date?: string | null;
          parent_invoice_id?: string | null;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          invoice_number?: string;
          client_id?: string;
          currency_id?: string;
          total_amount?: number;
          vat_rate?: number;
          vat_amount?: number;
          total_with_vat?: number;
          status?: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
          issue_date?: string;
          due_date?: string;
          payment_date?: string | null;
          notes?: string | null;
          terms_conditions?: string | null;
          is_recurring?: boolean;
          recurring_period?: 'monthly' | 'quarterly' | 'yearly' | null;
          next_invoice_date?: string | null;
          parent_invoice_id?: string | null;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      regular_payments: {
        Row: {
          id: string;
          name: string;
          type: 'income' | 'expense';
          amount: number;
          currency_id: string;
          category_id: string;
          frequency: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly';
          start_date: string;
          end_date: string | null;
          next_payment_date: string;
          is_active: boolean;
          description: string;
          notes: string | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: 'income' | 'expense';
          amount: number;
          currency_id: string;
          category_id: string;
          frequency: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly';
          start_date: string;
          end_date?: string | null;
          next_payment_date: string;
          is_active?: boolean;
          description: string;
          notes?: string | null;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'income' | 'expense';
          amount?: number;
          currency_id?: string;
          category_id?: string;
          frequency?: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly';
          start_date?: string;
          end_date?: string | null;
          next_payment_date?: string;
          is_active?: boolean;
          description?: string;
          notes?: string | null;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      company_settings: {
        Row: {
          id: string;
          user_id: string;
          company_name: string;
          tax_number: string | null;
          address: string | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          logo_url: string | null;
          default_currency_id: string;
          default_vat_rate: number;
          invoice_prefix: string | null;
          quote_prefix: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_name: string;
          tax_number?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          default_currency_id: string;
          default_vat_rate?: number;
          invoice_prefix?: string | null;
          quote_prefix?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          company_name?: string;
          tax_number?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          default_currency_id?: string;
          default_vat_rate?: number;
          invoice_prefix?: string | null;
          quote_prefix?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};
